version: "2"
services:
  iat-server:
    image: registry.cn-beijing.aliyuncs.com/niao/iat-server:1.0.0
    container_name: iat-server
    ports:
    - "5000:5000"
    links:
    - iat-mysql
    volumes:
    - /home/niaoshuai/docker_mnt/:/jmeter_log
    - /var/run/docker.sock:/var/run/docker.sock
  iat-mysql:
    image: mysql:5.6
    container_name: iat-mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_DATABASE=IAT
    - MYSQL_ROOT_PASSWORD=root
  iat-h5:
    image: registry.cn-beijing.aliyuncs.com/niao/iat-h5:1.0.0
    container_name: iat-h5
    ports:
    - "8000:8000"
    links:
    - iat-server
